name: Terraform Deploy to Prod

on:
  push:
    branches: [ main ]

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: eu-west-1
      TF_WORKSPACE: default

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init (S3 backend)
        run: |
          terraform init -reconfigure -input=false \
            -backend-config="bucket=infra-household-finances-tfstate" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=eu-west-1" \
            -backend-config="dynamodb_table=infra-household-finances-locks" \
            -backend-config="encrypt=true"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan (prod)
        run: terraform plan -input=false -no-color -lock-timeout=120s -var-file=envs/prod.tfvars

      - name: Terraform Apply (prod)
        run: terraform apply -auto-approve -input=false -lock-timeout=120s -var-file=envs/prod.tfvars
