name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (dev, staging, prod)"
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: eu-west-1
      ENV: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -reconfigure -input=false

      - name: Select or Create Workspace
        run: terraform workspace select ${{ env.ENV }} || terraform workspace new ${{ env.ENV }}

      - name: Terraform Validate
        run: terraform validate

      - name: Force unlock state
        run: terraform force-unlock -force 7d8dc4aa-4032-f940-fb02-9246a1c380ab || true

      - name: Terraform Refresh
        run: terraform refresh -var-file=envs/${{ env.ENV }}.tfvars

      - name: Terraform Plan
        run: terraform plan -input=false -var-file=envs/${{ env.ENV }}.tfvars

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -var-file=envs/${{ env.ENV }}.tfvars
