name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (dev, staging, prod)"
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    permissions:
      id-token: write    # 🔑 REQUIRED for OIDC
      contents: read     # usually needed to checkout code
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.2

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=envs/${{ github.event.inputs.environment }}.tfvars
