name: Terraform Deploy (Staging)

on:
  push:
    tags:
      - 'v*-rc*'   # e.g. v1.0.0-rc1

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: staging   # requires approval
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: eu-west-1
      ENV: staging

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}


      - run: terraform init -reconfigure -input=false
      - run: terraform workspace select ${{ env.ENV }} || terraform workspace new ${{ env.ENV }}
      - run: terraform apply -auto-approve -input=false -var-file=envs/${{ env.ENV }}.tfvars
