name: Terraform Deploy to Staging

on:
  workflow_dispatch: {}

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: eu-west-1
      ENV: staging
      TF_BUCKET: infra-household-finances-tfstate
      TF_LOCK_TABLE: infra-household-finances-locks

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # Ensure the DynamoDB lock table exists (idempotent)
      - name: Ensure DynamoDB lock table
        shell: bash
        run: |
          set -euo pipefail
          if ! aws dynamodb describe-table --table-name "$TF_LOCK_TABLE" >/dev/null 2>&1; then
            aws dynamodb create-table \
              --table-name "$TF_LOCK_TABLE" \
              --attribute-definitions AttributeName=LockID,AttributeType=S \
              --key-schema AttributeName=LockID,KeyType=HASH \
              --billing-mode PAY_PER_REQUEST
            aws dynamodb wait table-exists --table-name "$TF_LOCK_TABLE"
          fi

      # Init directly against the staging key
      - name: Terraform Init (S3 backend)
        run: |
          terraform init -reconfigure -input=false \
            -backend-config="bucket=${TF_BUCKET}" \
            -backend-config="key=env:/${ENV}/terraform.tfstate" \
            -backend-config="region=${AWS_REGION}" \
            -backend-config="dynamodb_table=${TF_LOCK_TABLE}" \
            -backend-config="encrypt=true"

      # No local workspaces when using a fixed S3 key – remove the workspace step

      - name: Terraform Plan
        run: terraform plan -input=false -var-file=envs/${{ env.ENV }}.tfvars

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -var-file=envs/${{ env.ENV }}.tfvars
