name: Deploy Infra

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to deploy (dev/staging/prod)"
        required: true
        type: choice
        options: [dev, staging, prod]

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS creds (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file=envs/${{ github.event.inputs.env }}.tfvars

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=envs/${{ github.event.inputs.env }}.tfvars

      - name: Save outputs for debugging
        run: terraform output
