name: Terraform Deploy (Prod)

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'   # e.g. v1.0.0 (no rc)

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: prod   # requires approval
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: eu-west-1
      ENV: prod

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init -reconfigure -input=false
      - run: terraform workspace select ${{ env.ENV }} || terraform workspace new ${{ env.ENV }}
      - run: terraform apply -auto-approve -input=false -var-file=envs/${{ env.ENV }}.tfvars
