name: Terraform Plan (PR)

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    env:
      AWS_REGION: eu-west-1
      ENV: dev

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init -reconfigure -input=false

      - run: terraform workspace select ${{ env.ENV }} || terraform workspace new ${{ env.ENV }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -var-file=envs/${{ env.ENV }}.tfvars

      - name: Comment Plan on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: terraform
          message: |
            ### Terraform Plan
            ```
            ${{ steps.plan.outputs.stdout }}
            ```
